### ISSUE TITLE
Add RuboCop for static code analysing

### ISSUE THREAD

**Issue by kasper** [testmycode/tmc-server#219]
It would be worth to enable static code analysing to keep the code base coherent. [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide/) provides very sensible guidelines. [RuboCop](https://github.com/bbatsov/rubocop/) follows these and has extensive checks with sensible defaults. We would only need to enable Rails cops and possibly disable code metric checks.

**File** `.rubocop.yml`
```yml
AllCops:
  RunRailsCops: true

# Metrics

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
```
