### ISSUE TITLE
Erroneous metadata config server problem

### ISSUE THREAD

**Issue by josalmi** [testmycode/tmc-server#220]
metadata.yml causing server to not render properly (500 Server Error)

```yml
unlocked_after: 85% of week1
courses:
  course-xxx:
    unlocked_after: nil
```
